### PR TITLE
feat: obscure authentication token

### PR DESCRIPTION
**Pull request by makinwab**
## Summary
Obscure authentication key in error logs.

## Motivation and Context
For security reasons.

## Todos

-   [x] Implemented feature
-   [ ] Feature with pending implementation

### CODE REVIEW

**Comment by AWolf81** [comment]
@makinwab I think I have an issue with the code added by this PR. 

I'm creating a demo (a create-react-app) that is querying data from Contentful and getting the data is working if there are no errors.

I changed the space id to a wrong id to test the error handling and I'm getting the error message `error.response.request._headers is undefined`.

It looks like there is a problem in [contentful.js at line 105](https://github.com/contentful/contentful.js/blob/master/lib/contentful.js#L105). `_headers` is undefined if I'm adding a breakpoint in the browser console at that line.

Is there anything I can do, that I'm getting the response from the server? In the network tab, there is the right response but it's not available so I can't display it as an error message.

You can find the demo [here](https://codesandbox.io/s/basic-contentful-example-react-app-tbty6). If you modify the space id in `.env` file you can get a successful response.

**Comment by makinwab** [comment]
Hi @AWolf81, I'm currently looking into this. 

In the meantime, if you need to move forward quickly, you can use v7.11.2 (assuming the latest version is the culprit).

**Comment by makinwab** [comment]
A fix addressing this issue has been fixed, @AWolf81. Please update to the latest version of contentful (v7.11.4) and confirm that all works as expected.

Thanks for raising this.

**Comment by AWolf81** [comment]
@makinwab you're welcome and thanks for the quick fix.

I think the fix is working (no more _headers is undefined error) but it would be great to have the server response in the error handler. 

At the moment, for an invalid token it's "Request failed with status code 401" but the response "The access token you send could not be found ..." would be better. 

grafik

The line in question is [lib/create-contentful-api.js#line 84](https://github.com/contentful/contentful.js/blob/master/lib/create-contentful-api.js#L84). I think the following snippet should fix that:
```js
  function errorHandler (error) {
    if (error.response.data) {
      throw error.response.data
    }
    throw error
  }
```

**Comment by makinwab** [comment]
@AWolf81, thanks for the feedback. We've now updated the library to throw the appropriate error data.

In the future, please feel free to create an issue and reference the necessary PRs or Links. It'll aid visibility and we can better track it. We also welcome pull requests 🙂.

**Comment by AWolf81** [comment]
@makinwab OK, sorry, next time if I have something I'll create an issue for it.

I wasn't sure if it's a bug or if it's an issue with my code that's why I asked here. 
Is there a way I can ask question somewhere e.g. Slack Channel, Gitter or Twitter?

**Comment by makinwab** [comment]
> @makinwab OK, sorry, next time if I have something I'll create an issue for it.
> 
> I wasn't sure if it's a bug or if it's an issue with my code that's why I asked here.

Oh no, please don't be sorry 😅. I'm not aware of any hard/strict rule here, I just thought to let you know of the common way.


> Is there a way I can ask question somewhere e.g. Slack Channel, Gitter or Twitter?

Yes, we have a [community slack group](https://www.contentful.com/slack/) that you can join and ask/answer questions.

**Comment by lfamorim** [comment]
@makinwab
This PR is non-sense. As programmers, we need to make all code understandable and avoid secret shortcuts, like the function obscureAuthTokenInResponse. This pull-request inserts a deprecated property from NodeJS since the 12 version and does not guarantee that there is no other secret leaking from the error, resuming, still insecure, and breaks production environments.

https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames

A logical suggestion to fix is to stop trying to modify the headers from the error to make safe. Simply creating a new error and using safe methods and properties, those who not begin with an underscore and exists in the documentation will do better in turning this library safe in error throwing.

```
lfamorim@lfamorim-bipbop:~/projects/bipbop-components/packages/screen-generator$ node --trace-deprecation dist/contentful-client.js
(node:18129) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at /home/lfamorim/projects/bipbop-components/packages/screen-generator/node_modules/contentful/dist/contentful.node.js:7610:34
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async retrieveLabel (/home/lfamorim/projects/bipbop-components/packages/screen-generator/dist/contentful-client.js:34:18)
(node:18129) UnhandledPromiseRejectionWarning: #<Object>
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:18129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```
```

**Pull request merged**
