### PR TITLE
test: make package json command check min files

### PR DESCRIPTION
**Pull request by Techn1x**
## Summary

See https://github.com/contentful/contentful.js/issues/1936

## Description

I am hopeful that this can be used as a failing test (circle CI should run `npm run build` which will run these check commands and fail)

## Screenshots (if appropriate):

Screenshot 2024-01-19 at 8 34 12 pm

### CODE REVIEW

**Comment by Techn1x** [comment]
@marcolink is this useful or should I close it?

**Comment by marcolink** [comment]
cc @mgoudy91

**Comment by Techn1x** [comment]
Would be great to see this fixed for a patch version. I did give it a go, but was only able to come up with the failing test.

**Comment by axe312ger** [comment]
This will be included in #2164

**Comment by Techn1x** [comment]
Thankyou! Can confirm underlying issue resolved in 10.9.0+

**Pull request closed without merging**
