### PR TITLE
fix: allow `nin` operator in metadata tag queries

### LINKED ISSUE #2197: Unable to query entries that do not include certain tags
## Expected Behavior
You should be able to query `'metadata.tags.sys.id[nin]': ['tag_id']` to exclude a tag.

## Actual Behavior
`'metadata.tags.sys.id[nin]': ['tag_id']` is an invalid query

## Possible Solution
Give us the ability to use the `nin` operator. It is already present in the Contentful App's filtering `filters.0.key=metadata.tags.sys.id&filters.0.op=nin`:
```
https://app.contentful.com/spaces/{space-id}/views/entries?searchText=&displayedFieldIds=name&displayedFieldIds=contentType&displayedFieldIds=updatedAt&displayedFieldIds=metadata.tags&order.direction=descending&order.fieldId=updatedAt&filters.0.key=metadata.tags.sys.id&filters.0.op=nin&filters.0.val=onboardingBlogPost
```

## Steps to Reproduce

1. Use contentful's `getEntries()`
2. Provide a query parameter to exclude a tag
```js
'metadata.tags.sys.id[nin]': ['your_tag_id'],
```
3. Confirm that the entry with `your_tag_id` was not excluded from the resuts

## Context

We're trying to query all blog posts while excluding the ones tagged with `onboardingBlogPost`.

A temporary solution is to use `metadata.tags[exists]: false` but that queries content without any tags, and we still want other tags to be visible in our blog page.

## Environment

-   **Language Version**:  `v20.10.0`
-   **Package Manager Version**:  `10.2.3`
-   **Browser Version**: 
-   **Operating System**:  `Darwin Tomass-MBP-2.lan 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64`
-   **Package Version**: `"contentful": "^10.6.3",`
-   **Which API are you using?**: Delivery

### PR DESCRIPTION
**Pull request by Toxicom**
## Summary
- Adds `[nin]` operator to metadata tags queries

## Description
Adds the `nin` type to MetadataTagsQueries.
I tested this on my local project by editing the `node_modules` and seems like just adding that one type fixed the TS issues I had while querying the correct data.

## Motivation and Context

Fixes #2197 

## Todos

-   [x] Add tests

### CODE REVIEW

**Review by jesseday — COMMENTED** [review]
Seems straightforward and useful to me.  @whitelisab are you the right person to review this?

**Review by veu — APPROVED** [review]
LGTM

**Comment by Toxicom** [comment]
@veu How can we get this merged? Are you able to see why codeclimate's failing?

**Comment by Toxicom** [comment]
@david-shibley-contentful what can I do to help merge this? 🤞

**Comment by t-col** [comment]
thank you for your contribution @Toxicom

**Pull request merged**
