### PR TITLE
Fix: Upstream `fetch` adapter for Axios

### PR DESCRIPTION
**Pull request by sgammon**
## Summary
Fix for upstream issues with Axios, which prevent Contentful from working in certain JavaScript contexts (fixes and closes contentful/contentful.js#395).

## Description
Because of the issue reported with contentful/contentful.js#395, caused by upstream issues with Axios (axios/axios#2081, axios/axios#1219, and axios/axios#484 for instance), this change switches the `axios` dependency in `package.json` to a [forked `axios`](axios/axios#2891) that supports the *Fetch API*.

## Motivation and Context
This is necessary to make `axios` (and, therefore, Contentful) work within the parameters of a WebWorker which does not have access to XHR (for instance, a [CloudFlare Worker](https://workers.cloudflare.com/)).

## Todos
- [x] Switched dependency to fork of Axios
- [x] Testing, docs, and so on

### CODE REVIEW

**Comment by sgammon** [comment]
the tests seem to pass locally - but CI isn't running. some official help would be great on this

**Comment by sgammon** [comment]
yo... contentful?

**Comment by phoebeschmidt** [comment]
Hi @sgammon, unfortunately in our current configuration, CI can't run for external contributions. We have some plans to fix this but unfortunately not enough time to work on it now.

Even so, this PR isn't mergeable-- we can't change axios to depend on your local fork and we won't remove the logic obscuring auth tokens in responses. 

I agree that Axios not functioning in CloudFlare workers is a problem for the SDK, and I'm sorry it's blocking you. To fix this we'll have to consider different solutions. It's in our backlog and I hope we will get a chance to work on it soon.

**Comment by sgammon** [comment]
@phoebeschmidt okay well the bug is actually that `fetch` is unavailable as an adapter. XHR is obviously old in the first place and carries with it some serious performance implications, in some cases.

fetch avoids these

**Comment by sgammon** [comment]
@phoebeschmidt as prospective customers for Contentful Enterprise we'd want this fixed, and we'd want to not be using XHR if we were using Contentful from the browser, which we have other plans to do. so we'd have to use our fork, and of course that means we have to manually apply and merge any updates that come from upstream

is there really no appetite to write a simple fetch adapter for contentful.js, and avoid use of Axios at all? i don't understand. all we want to do is use your software, and here is a fix - surely, if we can get the upstream PR merged in Axios, we won't have to depend on my fork.

so the real question is, are we willing to work toward fixing this on any reasonable timetable, or do you feel like our being blocked here just isn't important enough to actually get fixed?

**Comment by sgammon** [comment]
@phoebeschmidt if memory serves i removed the token obscuring logic because i couldn't get it to work properly, but there is nothing particularly excluding that logic from working (as far as I know)

with a minimal amount of support from your team we could work together to get that code working, which also eliminates one of the valid concerns you brought up with this PR.

**Pull request closed without merging**
